### ISSUE TITLE
关于误差回传

### ISSUE THREAD

**Issue by Tord-Zhang** [nailo2c/a3c#1]
`(policy_loss + 0.5 * value_loss).backward()`
您好，有个问题想请教一下，policy_loss+0.5*value_loss是一个只有一个数字的Variable?那么回传的时候怎么将误差传到actor和critic两个子网络？actor的输出维度是一维向量，长度为num_action,critic输出为一维向量，长度为1，那这个loss怎么通过输出长度为num_action的网络回传啊？

**Comment by nailo2c** [comment]
您好，我的理解是 policy_loss + 0.5 * value_loss 是object function，它是一個訓練神經網路的目標，在我們的case裡是希望這個值越小越好，因此這個值不會反向傳遞。

至於您說的在神經網路輸出值為多維向量時，back propagation如何運作，可以查網路相關教學，資源非常豐富。在atari的case中，reward的設計會影響到back propagation所回傳的誤差值，可以看Karpathy精彩的Policy Gradient教學，裡頭會講到reward如何設計、以及policy loss為何要這麼設計 http://karpathy.github.io/2016/05/31/rl/

但總歸來說pytorch包得實在太好了，只要短短一句就把automatic differentiation做完，因此對於神經網路的誤差是如何傳遞的產生疑問也是滿合理的。但我也還在學習中，以上見解也許會有錯誤，也請網路上諸位大神不吝指教，希望有幫助到你。
